const char particle_vertex_code[] =
   "#version 430 core\n"
   "layout(location=0) in vec3 vrt_position;\n"
   "layout(location=2) in vec2 vrt_texcoord;\n"
   "layout(std140, binding=1) uniform CameraUBO\n"
   "{\n"
   "   mat4 mat_view;\n"
   "   mat4 mat_proj;\n"
   "   mat4 mat_invview;\n"
   "   mat4 mat_invproj;\n"
   "   vec2 u_near_far;\n"
   "   uvec2 u_screen_size;\n"
   "   vec4 u_proj_info;\n"
   "};\n"
   "layout(std140, binding=2) uniform ModelUBO\n"
   "{\n"
   "   mat4 mat_model;\n"
   "   mat4 mat_invmodel;\n"
   "   mat4 mat_mvp;\n"
   "   mat4 mat_normal_model_u_color;\n"
   "};\n"
   "layout(std430, binding=3) restrict buffer ParticleSSBO\n"
   "{\n"
   "   mat4 mat_particle[];\n"
   "};\n"
   "out vec2 v2f_texcoord;\n"
   "void main()\n"
   "{\n"
   "   v2f_texcoord = vrt_texcoord;\n"
   "   gl_Position = mat_proj * mat_view * mat_particle[gl_InstanceID] * vec4(vrt_position, 1.0);\n"
   "}\n";

const char particle_fragment_code[] =
   "#version 430 core\n"
   "layout(binding=0) uniform sampler2D tex_color;\n"
   "layout(std140, binding=1) uniform CameraUBO\n"
   "{\n"
   "   mat4 mat_view;\n"
   "   mat4 mat_proj;\n"
   "   mat4 mat_invview;\n"
   "   mat4 mat_invproj;\n"
   "   vec2 u_near_far;\n"
   "   uvec2 u_screen_size;\n"
   "   vec4 u_proj_info;\n"
   "};\n"
   "layout(std140, binding=2) uniform ModelUBO\n"
   "{\n"
   "   mat4 mat_model;\n"
   "   mat4 mat_invmodel;\n"
   "   mat4 mat_mvp;\n"
   "   mat4 mat_normal_model_u_color;\n"
   "};\n"
   "float PixelID(vec2 screen_coord)\n"
   "{\n"
   "   screen_coord = floor(screen_coord);\n"
   "   vec2 m2 = mod(screen_coord, 2.0);\n"
   "   return abs(m2.x * 0.667 - m2.y);\n"
   "}\n"
   "float Bayer(vec2 screen_coord)\n"
   "{\n"
   "   float res = PixelID(screen_coord * 0.5) * 0.2;\n"
   "   res += PixelID(screen_coord) * 0.8;\n"
   "   return res;\n"
   "}\n"
   "in vec2 v2f_texcoord;\n"
   "out vec4 frg_color;\n"
   "void main()\n"
   "{\n"
   "   vec4 color = texture(tex_color, v2f_texcoord) * mat_normal_model_u_color[3];\n"
   "   float dither = mix(Bayer(vec2(gl_FragCoord.xy)) * 0.1, 1.0, 0.01);\n"
   "   if (color.a < dither)\n"
   "      discard;\n"
   "   frg_color.rgb = color.rgb * color.a;\n"
   "   frg_color.a = color.a;\n"
   "}\n";

const char particle_compute_code[] =
   "#version 430 core\n"
   "layout(local_size_x=1, local_size_y=1, local_size_z=1) in;\n"
   "layout(std140, binding=0) uniform GlobalUBO\n"
   "{\n"
   "   float u_time;\n"
   "};\n"
   "layout(std140, binding=1) uniform CameraUBO\n"
   "{\n"
   "   mat4 mat_view;\n"
   "   mat4 mat_proj;\n"
   "   mat4 mat_invview;\n"
   "   mat4 mat_invproj;\n"
   "   vec2 u_near_far;\n"
   "   uvec2 u_screen_size;\n"
   "   vec4 u_proj_info;\n"
   "};\n"
   "layout(std140, binding=2) uniform ModelUBO\n"
   "{\n"
   "   mat4 mat_model;\n"
   "   mat4 mat_invmodel;\n"
   "   mat4 mat_mvp;\n"
   "   mat4 mat_normal_model_u_color;\n"
   "};\n"
   "layout(std430, binding=3) buffer ParticleSSBO\n"
   "{\n"
   "   mat4 mat_particle[];\n"
   "};\n"
   "uint RandomHash(inout uint seed)\n"
   "{\n"
   "   seed ^= seed << 13u;\n"
	"   seed ^= seed >> 17u;\n"
	"   seed ^= seed << 5u;\n"
   "   return seed;\n"
   "}\n"
   "float Random(inout uint seed) { return float(RandomHash(seed)) * (1.0 / float(0xFFFFFFFFu)); }\n"
   "vec4 MakeQuat(vec3 axis, float angle)\n"
   "{\n"
   "   float a = angle * 0.5;\n"
   "   float b = sin(a);\n"
   "   float c = cos(a);\n"
   "   vec4 res = vec4(0.0);\n"
   "   res.xyz = axis * b;\n"
   "   res.w = c;\n"
   "   return res;\n"
   "}\n"
   "vec4 MulQuat(vec4 a, vec4 b)\n"
   "{\n"
   "   vec4 res = vec4(0.0);\n"
   "   res.xyz = (\n"
   "      ((b.xyz * a.w) + (a.xyz * b.w)) +\n"
   "      cross(a.xyz, b.xyz)\n"
   "   );\n"
   "   res.w = a.w * b.w - dot(a.xyz, b.xyz);\n"
   "   return res;\n"
   "}\n"
   "vec4 LookingAt(vec3 origin, vec3 target)\n"
   "{\n"
   "   const vec3 front = vec3(0, 0,-1);\n"
   "   const vec3 up = vec3(0, 1, 0);\n"
   "   vec3 pointing_dir = normalize(target - origin);\n"
   "   vec3 tan_dir = normalize(pointing_dir - (up * dot(pointing_dir, up)));\n"
   "   vec4 yaw_q = vec4(0, 0, 0, 1);\n"
   "   vec4 pitch_q = vec4(0, 0, 0, 1);\n"
   "   vec3 yaw_axis = normalize(cross(front, tan_dir));\n"
   "   if (dot(yaw_axis, yaw_axis) >= 0.000001)\n"
   "   {\n"
   "      float cos_angle = dot(front, tan_dir);\n"
   "      float angle = -acos(cos_angle);\n"
   "      yaw_q = MakeQuat(yaw_axis, angle);\n"
   "   } else {\n"
   "      yaw_axis = up;\n"
   "      float cos_angle = dot(front, tan_dir);\n"
   "      float angle = -acos(cos_angle);\n"
   "      yaw_q = MakeQuat(yaw_axis, angle);\n"
   "   }\n"
   "   if (abs(dot(pointing_dir, up)) > 0.001)\n"
   "   {\n"
   "      vec3 pitch_axis = normalize(cross(yaw_axis, tan_dir));\n"
   "      if (dot(pitch_axis, pitch_axis) > 0.0001)\n"
   "      {\n"
   "         pitch_axis = pitch_axis * sign(dot(pointing_dir, yaw_axis));\n"
   "         float cos_angle = dot(pointing_dir, tan_dir);\n"
   "         float angle = acos(cos_angle);\n"
   "         pitch_q = MakeQuat(pitch_axis, angle);\n"
   "      }\n"
   "   }\n"
   "   return normalize(MulQuat(yaw_q, pitch_q));\n"
   "}\n"
   "mat3 QuatToMat3(vec4 quaternion)\n"
   "{\n"
   "   float n = dot(quaternion, quaternion);\n"
   "   float s = 2.0f * ((n > 0.0) ? (1.0 / n) : 0.0);\n"
   "   float x = quaternion.x;\n"
   "   float y = quaternion.y;\n"
   "   float z = quaternion.z;\n"
   "   float w = quaternion.w;\n"
   "   return mat3(\n"
   "      1.0-(y*y + z*z) * s, (x*y - w*z) * s, (x*z + w*y) * s,\n"
   "      (x*y + w*z) * s, 1.0-(x*x + z*z) * s, (y*z - w*x) * s,\n"
   "      (x*z - w*y) * s, (y*z + w*x) * s, 1.0-(x*x + y*y) * s\n"
   "   );\n"
   "}\n"
   "mat3 LookingAtMatrix(vec3 origin, vec3 target)\n"
   "{\n"
   "   return QuatToMat3(LookingAt(origin, target));\n"
   "}\n"
   "vec3 GetOrigin(mat4 matrix)\n"
   "{\n"
   "   return (matrix * vec4(0.0, 0.0, 0.0, 1.0)).xyz;\n"
   "}\n"
   "mat3 TransposeBasis(mat4 matrix)\n"
   "{\n"
   "   return mat3(\n"
   "      vec3(matrix[0].x, matrix[1].x, matrix[2].x),\n"
   "      vec3(matrix[0].y, matrix[1].y, matrix[2].y),\n"
   "      vec3(matrix[0].z, matrix[1].z, matrix[2].z)\n"
   "   );\n"
   "}\n"
   "mat4 NormalizedBasis(mat4 matrix)\n"
   "{\n"
   "   matrix[0].xyz = normalize(matrix[0].xyz);\n"
   "   matrix[1].xyz = normalize(matrix[1].xyz);\n"
   "   matrix[2].xyz = normalize(matrix[2].xyz);\n"
   "   return matrix;\n"
   "}\n"
   "void main()\n"
   "{\n"
   "   uint seed = (gl_WorkGroupID.x * 3 + 1);\n"
   "   float timer = u_time * 0.001;\n"
   "   float x = (sin(Random(seed) * 128.0 + timer * 11.0) *-cos(Random(seed) * 128.0 + timer * 25.0));\n"
   "   float y = (sin(Random(seed) * 128.0 + timer * 17.0) * sin(Random(seed) * 128.0 + timer * 21.0));\n"
   "   float z = (cos(Random(seed) * 128.0 + timer * 13.0) * sin(Random(seed) * 128.0 + timer * 24.0));\n"
   "   float len = (inversesqrt(x*x + y*y + z*z) * 3.0 + 180.0 * Random(seed));\n"
   "   x *= len;\n"
   "   y *= len;\n"
   "   z *= len;\n"

   "   mat4 model = NormalizedBasis(mat_model);\n"
   "   vec3 particle = GetOrigin(model) + mat3(model) * vec3(x, y, z);\n"
   "   vec3 camera = GetOrigin(mat_invview);\n"
   "   float view_depth = -(mat_view * vec4(particle, 1.0)).z;\n"
   "   float z_scaler = clamp(mix(view_depth, 1.0, 0.98), 0.0, 5.0);\n"
   "   mat3 model_scale = TransposeBasis(model) * mat3(mat_model) * z_scaler;\n"
   "   model = mat4(LookingAtMatrix(particle, camera) * model_scale);\n"
   "   model[3].xyz = particle;\n"

   "   mat_particle[gl_WorkGroupID.x] = model;\n"
   "}\n";
   