#ifndef SCN_DEFAULT_SHADERS
#define SCN_DEFAULT_SHADERS

const char builtin_vertex_code[] =
   "#version 430 core\n"
   "#define USE_LIGHTING\n"
   "layout(location=0) in vec3 vrt_position;\n"

   "#ifdef USE_LIGHTING\n"
   "layout(location=1) in vec3 vrt_normal;\n"
   "layout(location=3) in vec4 vrt_tangent;\n"
   "#endif // USE_LIGHTING\n"

   "layout(location=2) in vec2 vrt_texcoord;\n"
   "layout(std140, binding=1) uniform CameraUBO\n"
   "{\n"
   "   mat4 mat_view;\n"
   "   mat4 mat_proj;\n"
   "   mat4 mat_invview;\n"
   "   mat4 mat_invproj;\n"
   "   vec2 u_near_far;\n"
   "   uvec2 u_screen_size;\n"
   "   vec4 u_proj_info;\n"
   "};\n"
   "layout(std140, binding=2) uniform ModelUBO\n"
   "{\n"
   "   mat4 mat_model;\n"
   "   mat4 mat_invmodel;\n"
   "   mat4 mat_mvp;\n"
   "   mat4 mat_normal_model_u_color;\n"
   "};\n"
   "out vec2 v2f_texcoord;\n"

   "#ifdef USE_LIGHTING\n"
   "out vec3 v2f_normal;\n"
   "out vec3 v2f_tangent;\n"
   "out vec3 v2f_bitangent;\n"
   "out vec3 v2f_position;\n"
   "#endif // USE_LIGHTING\n"

   "void main()\n"
   "{\n"
   "   v2f_texcoord = vrt_texcoord;\n"
   "   gl_Position = mat_mvp * vec4(vrt_position, 1.0);\n"

   "#ifdef USE_LIGHTING\n"
   "   vec3 vs_normal = mat3(mat_view) * mat3(mat_normal_model_u_color) * vrt_normal;\n"
   "   vec3 vs_tangent = mat3(mat_view) * mat3(mat_normal_model_u_color) * vrt_tangent.xyz;\n"
   "   v2f_normal = vs_normal;\n"
   "   v2f_tangent = vs_tangent;\n"
   "   v2f_bitangent = cross(vs_normal, vs_tangent) * vrt_tangent.w;\n"
   "   v2f_position = (mat_view * mat_model * vec4(vrt_position, 1.0)).xyz;\n"
   "#endif // USE_LIGHTING\n"

   "}\n";

const char builtin_fragment_code[] =
   "#version 430 core\n"
   "#define USE_LIGHTING\n"
   "layout(binding=0) uniform sampler2D tex_color;\n"
   "layout(std140, binding=1) uniform CameraUBO\n"
   "{\n"
   "   mat4 mat_view;\n"
   "   mat4 mat_proj;\n"
   "   mat4 mat_invview;\n"
   "   mat4 mat_invproj;\n"
   "   vec2 u_near_far;\n"
   "   uvec2 u_screen_size;\n"
   "   vec4 u_proj_info;\n"
   "};\n"
   "layout(std140, binding=2) uniform ModelUBO\n"
   "{\n"
   "   mat4 mat_model;\n"
   "   mat4 mat_invmodel;\n"
   "   mat4 mat_mvp;\n"
   "   mat4 mat_normal_model_u_color;\n"
   "};\n"
   "in vec2 v2f_texcoord;\n"

   "#ifdef USE_LIGHTING\n"
   "layout(binding=1) uniform sampler2D tex_normal;\n"
   "in vec3 v2f_normal;\n"
   "in vec3 v2f_tangent;\n"
   "in vec3 v2f_bitangent;\n"
   "in vec3 v2f_position;\n"
   // "struct Cluster\n"
   // "{\n"
   // "   uvec4 frustum_info;\n"
   // "   vec4 min_bound;\n"
   // "   vec4 max_bound;\n"
   // "   uint indices[200];\n"
   // "};\n"
   // "struct PointLight\n"
   // "{\n"
   // "   vec4 origin_radius;\n"
   // "   uint rgbe_color; // RGBE encoded HDR color value\n"
   // "   float cos_half_angle; // cosine of spotlight cone angle\n"
   // "   float theta_radians; // angle theta in radians\n"
   // "   float phi_radians; // angle phi in radians\n"
   // "};\n"
   // "layout(std430, binding=1) restrict buffer ClusterSSBO\n"
   // "{\n"
   // "   uvec4 u_cluster_dimensions;\n"
   // "   Cluster u_clusters[];\n"
   // "};\n"
   // "layout(std430, binding=2) restrict buffer LightSSBO\n"
   // "{\n"
   // "   PointLight lights[];\n"
   // "};\n"
   // "vec3 DecodeColor(uint rgbe_color)\n"
   // "{\n"
   // "   const uint byte_mask = 255u;\n"
   // "   if (rgbe_color == 0) return vec3(0.0);\n"
   // "   uvec4 v = uvec4(\n"
   // "      (rgbe_color >>  0) & byte_mask,\n"
   // "      (rgbe_color >>  8) & byte_mask,\n"
   // "      (rgbe_color >> 16) & byte_mask,\n"
   // "      (rgbe_color >> 24) & byte_mask\n"
   // "   );\n"
   // "   float f = pow(2.0, float(v.w) - 136.0)\n;"
   // "   return vec3(v.xyz) * f;\n"
   // "}\n"
   "float PointAttenution(vec3 light_position)\n"
   "{\n"
   "   return pow(clamp(1.0 - dot(light_position, light_position), 0.0, 1.0), 4.0);\n"
   "}\n"
   // "float SpotAttenuation(vec3 light_vector, float theta, float phi, float cos_half_angle, float softness)\n"
   // "{\n"
   // "   if (cos_half_angle <= 0.9998)\n"
   // "      return 1.0;\n"
   // "   cos_half_angle = cos_half_angle * 0.5 + 0.5;\n"
   // "   vec4 cs_polar = -vec4(cos(theta), sin(theta), cos(phi), sin(phi));\n"
   // "   vec3 light_direction = vec3(cs_polar.y*cs_polar.z, cs_polar.w, cs_polar.x*cs_polar.z);\n"
   // "   float spot_dist = dot(light_vector, light_direction) * 0.5 + 0.5;\n"
   // "   return smoothstep(min(cos_half_angle * (1.0 + softness), 1.0), cos_half_angle, spot_dist);\n"
   // "}\n"
   "float SpecularHighlight(float gloss, float nDh)\n"
   "{\n"
   "   float u = nDh * nDh;\n"
   "   float u_sqr = u * u;\n"
   "   float gloss_sqr = gloss * gloss;\n"
   "   float gloss_cbe = gloss_sqr * gloss;\n"
   "   float roughness = 1.0 - gloss;\n"
   "   float a = roughness * roughness;\n"
   "   float a_sqr = a * a;\n"
   "   float normalizer = 1.0 / max(1.0 - gloss_sqr + a_sqr, gloss - u);\n"
   "   float blob = max(0.0, nDh * (roughness + u_sqr * gloss) - gloss_cbe) * normalizer;\n"
   "   blob *= blob * blob;\n"
   "   return blob * blob;\n"
   "}\n"
   "#endif // USE_LIGHTING\n"

   "out vec4 frg_color;\n"
   "void main()\n"
   "{\n"
   "   vec4 color = texture(tex_color, v2f_texcoord) * mat_normal_model_u_color[3];\n"

   "#ifdef USE_LIGHTING\n"
   "   vec3 final_color = color.rgb * 0.1;\n"
   "   vec3 normalmap = texture(tex_normal, v2f_texcoord).rgb * 2.0 - 1.0;\n"
   "   mat3 tbn = mat3(normalize(v2f_tangent), normalize(v2f_bitangent), normalize(v2f_normal));\n"
   "   vec3 position = v2f_position;\n"
   "   vec3 view = normalize(-v2f_position);\n"
   "   vec3 normal = tbn * normalize(normalmap);\n"
   // "   vec2 tile_size = vec2(u_screen_size) / vec2(u_cluster_dimensions.xy);\n" 
   // "   uint z_id = uint((log(abs(surface.position.z) / u_near_far.x) * u_cluster_dimensions.z) / log(u_near_far.y / u_near_far.x));\n"   
   // "   uvec3 tile = uvec3(gl_FragCoord.xy / tile_size, z_id);\n"
   // "   uint tile_id = (tile.y * u_cluster_dimensions.x) + (tile.z * u_cluster_dimensions.x * u_cluster_dimensions.y) + tile.x;\n"
   // "   uint light_count = clusters[tile_id].frustum_info.w;\n"
   // "   for (uint light_i=0; light_i<light_count; light_i++)\n"
   // "   {\n"
   // "      uint light_idx = clusters[tile_id].indices[light_i];\n"
   // "      PointLight light = lights[light_idx];\n"
   // "      vec3 light_origin = (mat_view * vec4(light.origin_radius.xyz, 1.0)).xyz;\n"
   // "      float light_radius = = light.origin_radius.w;\n"
   // "      vec3 light_position = (light_origin - position) / light_radius;\n"
   // "      vec3 light_vector = normalize(light_position);\n"
   // "      vec3 halfway = normalize(light_vector + view);\n"
   // "      float nDl = max(0.0, dot(normal, light_vector));\n"
   // "      float nDh = max(0.0, dot(normal, halfway));\n"
   // "      float attenuation = PointAttenution(light_position) * SpotAttenuation(light_vector, light.theta_radians, light.phi_radians, light.cos_half_angle, 0.0);\n"
   // "      vec3 light_color = DecodeColor(light.rgbe_color);\n"
   // "      final_color += (color.rgb + pow(nDh, 64.0)) * light_color * nDl;\n"
   // "   }\n"
   "      vec3 light_origin = (mat_view * vec4(1.0, 2.0,-1.0, 1.0)).xyz;\n"
   "      float light_radius = 10.0;\n"
   "      vec3 light_position = (light_origin - position) / light_radius;\n"
   "      vec3 light_vector = normalize(light_position);\n"
   "      vec3 halfway = normalize(light_vector + view);\n"
   "      float nDl = max(0.0, dot(normal, light_vector));\n"
   "      float nDh = max(0.0, dot(normal, halfway));\n"
   "      float attenuation = PointAttenution(light_position);\n"
   "      vec3 light_color = vec3(1.0) * attenuation;\n"
   "      float spec = SpecularHighlight(0.4, nDh);\n"
   "      final_color += (color.rgb + color.rgb * spec) * light_color * nDl;\n"
   // "      final_color = normal * 0.5 + 0.5;\n"
   "#else\n"
   "   vec3 final_color = color.rgb;\n"
   "#endif // USE_LIGHTING\n"

   "   frg_color.rgb = final_color * color.a;\n"
   "   frg_color.a = color.a;\n"
   "}\n";

#endif
